language: node_js
sudo: false

node_js:
  - 11
  - 10
  - 9
  - 8
  - 7

install:
  - npm install

# command to run tests
script:
  - grunt tslint
  - grunt swagger-validate
  - grunt build
  - npm test
  - npm run coveralls
