language: node_js

node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
env:
  - CC=clang CXX=clang++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libssl-dev
      - gcc-4.9-multilib
      - g++-4.9-multilib

install:
  - npm install

# command to run tests
script:
  - grunt tslint
  - grunt swagger-validate
  - grunt build
  - npm test
  - npm run coveralls
